### ISSUE TITLE
Player(Character) UI

### ISSUE THREAD

**Issue by stgte** [ithaca-comp-345/Game_Masters_Friend#31]

**Comment by ElvinLord12** [comment]
Epic

**Comment by mramir3z** [comment]
4/40 - 1 hour both writing and planning class structure

**Comment by ccantoral2121** [comment]
2 hours  - worked in connecting the frame for the character editor, 
TODO//
-created buttons to save, randomize and delete character stats.

**Comment by ccantoral2121** [comment]
3 hours -  updating landing page with  the new character name, fixing bugs

**Comment by ccantoral2121** [comment]
1 hour  - confirmation box when saving added
