### ISSUE TITLE
GameMasterUI

### ISSUE THREAD

**Issue by stgte** [ithaca-comp-345/Game_Masters_Friend#32]

**Comment by ElvinLord12** [comment]
Epic

**Comment by ElvinLord12** [comment]
Done when the software is a helper to a gamemaster, not a complete replacement but helps with the data and information management and nuance

**Comment by ElvinLord12** [comment]
Spent 3 hours working on cleaning up the api and ui aspects that weren't already implemented for some reason

**Comment by ElvinLord12** [comment]
spent 2 hours on the basic login ui and functionality
learned swing structure

**Comment by ElvinLord12** [comment]
logged 8 hours on piecing it all together
