### ISSUE TITLE
Attack roll

### ISSUE THREAD

**Issue by ElvinLord12** [ithaca-comp-345/Game_Masters_Friend#36]

**Comment by ElvinLord12** [comment]
Done when one character can attack another

**Comment by ElvinLord12** [comment]
child of #35

**Comment by ccantoral2121** [comment]
30 minutes in last session, attackRoll dice added, working on having the calculation done based on PvP and PvNPC

**Comment by ccantoral2121** [comment]
it's completed

**Comment by ccantoral2121** [comment]
5 hours
